apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: pps7lxwcx-go 
  janus-idp.io/tekton: pps7lxwcx-go
  backstage.io/kubernetes-id: pps7lxwcx-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pps7lxwcx-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml