apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pps7lxwcx-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:5727f0743fbbd30e8f57bd29d728aaf70191eb78@sha256:9bbe3fc2ef7bed2d0d74623e01f7880adfdc9c24e6f0ad6bd9d471739136b051
          name: container-image
